### ISSUE TITLE
clone repo

### ISSUE THREAD

**Issue by cdbBinary** [ember-cli/ember-disable-prototype-extensions#9]
Hi,

Im pretty new at all this but then not so new, but new enough. I'm not sure a lot of times when I get instructions, that a lot of stuff should be already known. When you say to 'git clone repository' 'npm install' 'bower install'. Do you to: git clone repo from inside app directory, then when I run npm install and bower install it will install this package in the app? Don't mean to ask stupid question.

**Comment by stefanpenner** [comment]
i'll update the readme, those instructions are for collaboration with this addon itself.

For using it you must only run `ember install ember-disable-prototype-extensions`
